name: unifi
version: '5.12.66'
summary: Unifi Network controller software.
description: |
  Unifi Network controller software.
base: core18
confinement: strict
grade: stable

parts:
  mongodb:
    plugin: nil
    source: https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.6/multiverse/binary-amd64/mongodb-org-server_3.6.17_amd64.deb

  unifi:
    plugin: nil
    stage-packages: [openjdk-8-jre, jsvc]
    source: https://dl.ui.com/unifi/5.12.66/unifi_sysvinit_all.deb

# apps:
#   start-unifi:
#     command: 
#     daemon: simple